app/src/signup/models.py
from app.src import db,login_manager
from sqlalchemy import Column, Integer, String, Float, DateTime
from flask_login import UserMixin
from flask_bcrypt import Bcrypt

bcrypt = Bcrypt()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    

class User(UserMixin, db.Model):
    __tablename__ = "users"
    
    id = Column("id", Integer, primary_key=True, autoincrement=True)
    username = Column("username", String(255), nullable=False)
    email = Column("email", String(255), nullable=False, unique=True)
    age = Column("age", Integer)
    password = Column("password", String(255), nullable=False)
    #image = Column(LargeBinary)
    #createdAt = Column("createdAt", DateTime)
    #updatedAt = Column("updatedAt", DateTime)

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password


    @classmethod
    def add_user(cls, username, email, password):
        hashed_password = bcrypt.generate_password_hash(password)
        user = cls(username=username, email=email, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        return user



#@app.before_request
#def set_login_user_name():
#    global login_user_name
#    login_user_name = current_user.username if current_user.is_authenticated else None

app/src/user_account/models.py
from app.src import db,login_manager
from sqlalchemy.orm import Mapped, mapped_column, relationship
from flask_login import UserMixin
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash, check_password_hash
from typing import List
from uuid import uuid4
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = "users"
    
    id: Mapped[int] = mapped_column(db.Integer, primary_key=True, autoincrement=True)
    username: Mapped[str] = mapped_column(db.String(255), nullable=False)
    email: Mapped[str] = mapped_column(db.String(255), nullable=False, unique=True)
    password: Mapped[str] = mapped_column(db.String(255), nullable=False)
    age: Mapped[int] = mapped_column(db.Integer, nullable=True)
    image_path: Mapped[str] = mapped_column(db.Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(db.DateTime, default=datetime.now)
    updated_at: Mapped[datetime] = mapped_column(db.DateTime, default=datetime.now)
    movies: Mapped[List["Movie"]] = relationship(back_populates="user")

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password

    #ユーザー追加
    @classmethod
    def add_user(cls, username, email, password):
        try:
            #引数で渡されたパスワードをハッシュ化
            hashed_password = generate_password_hash(password)

            #Userインスタンス作成&ユーザー追加・コミット
            user = cls(username=username, email=email, password=hashed_password)
            db.session.add(user)
            db.session.commit()
            return user
        
        except IntegrityError as sqlalchemy_error:
            #db.session.rollback()
            user = None
            return user
    
    #メールアドレスが一致するユーザーを取得
    @classmethod
    def select_by_email(cls, email):
        return cls.query.where(cls.email == email).one_or_none()
    
    #@classmethod
    #def select_by_id(cls, id):
    #    return cls.query.where(cls.id == id).one_or_none()
    
    #DB内のハッシュ化済みパスワードと渡されてきたパスワードを比較
    def check_password(self, password):
        return check_password_hash(self.password, password)

app/src/signup/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo

class SignupForm(FlaskForm):
    username = StringField("名前", validators=[DataRequired()])
    email = StringField("メールアドレス", validators=[DataRequired(), Email("メールアドレスを設定してください")])
    password = PasswordField("パスワード", validators=[DataRequired(), EqualTo("password_confirm", message="パスワードが一致しません")])
    password_confirm = PasswordField("パスワード確認", validators=[DataRequired()])
    submit = SubmitField("登録")

app/src/user_account/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo

class SignupForm(FlaskForm):
    username = StringField("名前", validators=[DataRequired()])
    email = StringField("メールアドレス", validators=[DataRequired(), Email("メールアドレスの形式が正しくありません")])
    password = PasswordField("パスワード", validators=[DataRequired(), EqualTo("password_confirm", message="パスワードが一致しません")])
    password_confirm = PasswordField("パスワード確認", validators=[DataRequired()])
    submit = SubmitField("登録")

class LoginForm(FlaskForm):
    email = StringField("メールアドレス", validators=[DataRequired(), Email("メールアドレスの形式が正しくありません")])
    password = PasswordField("パスワード", validators=[DataRequired()])
    submit = SubmitField("ログイン")


class UserForm(FlaskForm):
    username = StringField("名前", validators=[DataRequired()])
    email = StringField("メール", validators=[DataRequired(), Email("メールアドレスの形式が正しくありません")])
    password = PasswordField("パスワード", validators=[DataRequired(), EqualTo("password_confirm", message="パスワードが一致しません")])
    password_confirm = PasswordField("パスワード確認", validators=[DataRequired()])
    submit = SubmitField("更新")

app/src/user_account/__init__.py
from flask import Blueprint

signup_bp = Blueprint("signup", __name__, template_folder='templates')
login_bp = Blueprint("login", __name__, template_folder='templates')
user_bp = Blueprint("user", __name__, template_folder='templates')

from .import views, models

app/src/user_account/views.py
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from . import signup_bp, login_bp, user_bp
from .forms import SignupForm, LoginForm, UserForm
from .models import User
from datetime import timedelta
from app.src import db
from werkzeug.security import generate_password_hash
from app.src.movie.models import Movie

@signup_bp.route("/signup", methods=["GET", "POST"])
def signup():
    form = SignupForm(request.form)
    if request.method == "GET":
        return render_template("user_account/signup.html", form=form)
    
    elif request.method == "POST" and form.validate_on_submit():
        #Usersテーブルにユーザー追加
        user = User.add_user(form.username.data, form.email.data, form.password.data)
        
        if user:
            #ユーザーログイン
            login_user(user, remember=True, duration=timedelta(seconds=600))
            flash("登録しました", "primary")
            return redirect(url_for('user.user'))
        
        else:
            flash("メールアドレスがすでに存在しています", "danger")
            return render_template("user_account/signup.html", form=form)
    
    return render_template("user_account/signup.html", form=form)


@login_bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm(request.form)
    if request.method == "GET":
        #ログインページ表示
        return render_template("user_account/login.html", form=form)
    
    elif request.method == "POST" and form.validate_on_submit():
        #メールアドレスが一致するユーザーを取得
        user = User.select_by_email(form.email.data)

        #ユーザー存在確認&パスワード一致確認
        if user and user.check_password(form.password.data):

            #ユーザーログイン
            login_user(user, remember=True, duration=timedelta(seconds=600))
            flash("ログインしました", "primary")
            return redirect(url_for("user.user"))
        else:
            flash("ユーザーが存在しません", "danger")
            return render_template("user_account/login.html", form=form)
    
    return render_template("user_account/login.html", form=form)


@user_bp.route("/user")
@login_required
def user():
    return render_template("user_account/user.html")


@user_bp.route("/user/edit", methods=["GET", "POST"])
@login_required
def user_edit():
    form = UserForm(request.form)
    if request.method == "GET":
        #ユーザー編集ページ表示
        return render_template("user_account/user_edit.html", form=form)
    
    elif request.method == "POST" and form.validate_on_submit():

        #メールアドレスが一致するユーザーを取得
        user = User.select_by_email(current_user.email)

        if user:
            #各種値を変数格納
            user.username = form.username.data
            user.email = form.email.data
            user.password = generate_password_hash(form.password.data)

            #DBコミット
            db.session.commit()
            flash("ユーザー情報を更新しました")
            return render_template("user_account/user_edit.html", form=form)
        else:
            flash('ユーザーが存在しません','danger')
            return render_template("user_account/user_edit.html", form=form)

    return render_template("user_account/user_edit.html", form=form)
    

@user_bp.route("/user/delete", methods=["POST", "GET"])
@login_required
def user_delete():
    if request.method == "POST":
        #ユーザーに紐づく映画をすべて削除
        movies = Movie.query.where(Movie.user_id == current_user.id).all()

        #複数レコードデリート&コミット
        for movie in movies:
            db.session.delete(movie)
        
        db.session.commit()

        #メールアドレスが一致するユーザーを取得
        user = User.select_by_email(current_user.email)
        
        #ユーザデリート&コミット
        db.session.delete(user)
        db.session.commit()
        #ユーザーログアウト
        logout_user()
        
        flash("ユーザーを削除しました")
        return render_template("home/index.html")
    
    return render_template("home/index.html")


@login_bp.route("/logout", methods=["GET"])
@login_required
def logout():

    #ユーザーログアウト
    logout_user()
    flash("ログアウトしました", 'success')
    return render_template("home/index.html")

app/src/templates/user_account/login.html
{% from 'bootstrap5/form.html' import render_form %}
{% from 'bootstrap5/form.html' import render_form_row %}
{% from 'bootstrap5/utils.html' import render_messages %}
{% extends "base.html" %}

{% block title %}
Movie-Record-App_login
{% endblock %}

{% block content %}
    {# フラッシュメッセージとエラーメッセージの表示機能 #}
    {{ render_messages(container=True, dismissible=True, dismiss_animate=True) }}

    {# ログインフォーム(メールアドレスとパスワード) #}
    <div class="container mx-auto">
            <div class="m-4">
            <form method="post">        
                {{ form.csrf_token() }}
                {{ render_form_row([form.email]) }}
                {{ render_form_row([form.password]) }}
                {{ render_form_row([form.submit]) }}
            </form>
        </div>
    </div>
{% endblock %}

app/src/templates/user_account/signup.html
{% from 'bootstrap5/form.html' import render_form %}
{% from 'bootstrap5/utils.html' import render_messages %}
{% extends "base.html" %}

{% block title %}
Movie-Record-App_signup
{% endblock %}

{% block content %}
    {# フラッシュメッセージとエラーメッセージの表示機能 #}
    {{ render_messages(container=True, dismissible=True, dismiss_animate=True) }}

    {# ログインフォーム(メールアドレスとパスワード) #}
    <div class="container">
        {{ render_form(form) }}
    </div>
{% endblock %}

app/src/templates/user_account/user.html
{% from 'bootstrap5/form.html' import render_form %}
{% from 'bootstrap5/form.html' import render_form_row %}
{% from 'bootstrap5/utils.html' import render_messages %}
{% extends "base.html" %}

{% block title %}
Movie-Record-App_user
{% endblock %}

{% block content %}
    {# フラッシュメッセージとエラーメッセージの表示機能 #}
    {{ render_messages(container=True, dismissible=True, dismiss_animate=True) }}

    <div class="container">
        <div class="card m-4">
            <div class="card-header fs-2">
            視聴記録
            </div>
            <div class="card-body">
                <h5 class="card-title">映画を通した英語学習でモチベーションを保つ</h5>
                <p class="card-text">日々の記録をつけて映画による英語学習のモチベーションを保ちましょう。また、つけた記録とは別に洋画の字幕も確認できます。</p>
                <a href="{{url_for('record.record')}}" class="btn btn-primary">視聴記録を見る</a>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="card m-4">
            <div class="card-header fs-2">
            映画検索
            </div>
            <div class="card-body">
                <h5 class="card-title">視聴した映画を検索してみましょう</h5>
                <p class="card-text">あなたが見た映画を検索してみましょう。そのまま視聴記録として登録することもできます。</p>
                <a href="{{url_for('search.search')}}" class="btn btn-primary">映画を検索する</a>
            </div>
        </div>
    </div>
{% endblock %}

app/src/templates/user_account/user_edit.html
{% from 'bootstrap5/form.html' import render_form_row %}
{% from 'bootstrap5/utils.html' import render_messages %}
{% extends "base.html" %}

{% block title %}
Movie-Record-App_user-edit
{% endblock %}

{% block content %}
    {# フラッシュメッセージとエラーメッセージの表示機能 #}
    {% if form.errors %}
        <div class="container flashed-messages">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        {% for error in form.errors.username %}
                            <div>{{ error }}</div>
                        {% endfor %}
                        {% for error in form.errors.email %}
                            <div>{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="container flashed-messages">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        {% for message in messages %}
                            <div>{{ message }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    {% endwith %}

    {# ログインフォーム(メールアドレスとパスワード) #}
    <div class="container">
        <form method="POST">
            {{ form.csrf_token }}

            <div class="row">
                <div class="col">
                    <div class="mb-3 required">
                        <label class="form-label" for="username">名前</label>
                        <input class="form-control" id="username" name="username" required type="text" value={{current_user.username}}>
                     </div>
                </div>
            <div class="row">
            <div class="col">
                <div class="mb-3 required">
                    <label class="form-label" for="email">メール</label>
                    <input class="form-control" id="email" name="email" required type="text" value={{current_user.email}}>
                </div>
            </div>
            {{ render_form_row([form.password]) }}
            {{ render_form_row([form.password_confirm]) }}
            {{ render_form_row([form.submit], button_style="primary") }}
        </form>
        <div class="mt-4 pull-right">
            <form action="{{url_for('user.user_delete') }}" method="POST">
                <button type="submit" class="btn btn-danger">退会する</button>
            </form>
        </div>
    </div>
        
{% endblock %}