app/src/movie/models.py
from app.src import db
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.src.user_account.models import User
from datetime import datetime

class Movie(db.Model):
    __tablename__ = "movie"
    
    id: Mapped[int] = mapped_column(db.Integer, primary_key=True, autoincrement=True)
    title: Mapped[str] = mapped_column(db.String(500), nullable=True)
    overview: Mapped[str] = mapped_column(db.String(2000), nullable=True)
    comment: Mapped[str] = mapped_column(db.String(2000), nullable=True)
    date: Mapped[datetime] = mapped_column(db.DateTime, default=datetime.now)
    movie_number: Mapped[int] = mapped_column(db.Integer, nullable=False)
    poster_path: Mapped[str] = mapped_column(db.String(100), nullable=True)
    user_id: Mapped[int] = mapped_column(db.Integer, db.ForeignKey('users.id'))
    user: Mapped["User"] = relationship(back_populates="movies")
    

    def __init__(self, title, overview, comment, date, movie_number, poster_path, user_id):
        self.title = title
        self.overview = overview
        self.comment = comment
        self.date = date
        self.movie_number = movie_number
        self.poster_path = poster_path
        self.user_id = user_id
    
    #映画追加
    @classmethod
    def add_movie(cls, title, overview, comment, date, movie_number, poster_path, user_id):
        movie = cls(
                title = title,
                overview = overview,
                comment=comment,
                date=date,
                movie_number=movie_number,
                poster_path=poster_path,
                user_id=user_id)
        
        db.session.add(movie)
        db.session.commit()

app/src/movie/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, HiddenField, TextAreaField, DateField
from wtforms.validators import DataRequired

class MovieForm(FlaskForm):
    title = HiddenField("タイトル")
    overview = HiddenField("あらすじ")
    comment = TextAreaField('コメント：', validators=[DataRequired()])
    date = DateField('鑑賞日付:', validators=[DataRequired()])
    poster_path = HiddenField("", validators=[DataRequired()])
    submit = SubmitField("登録")

app/src/movie/__init__.py
from flask import Blueprint

movie_bp = Blueprint("movie", __name__, template_folder='templates')

from .import views, models

app/src/movie/views.py
from flask import render_template, request, redirect, url_for, flash
from . import movie_bp
from flask_login import login_required, current_user
from .. import api3
from .forms import MovieForm
from app.src.user_account.models import User
from .models import Movie

#@movie_bp.route("/movie", methods=["GET"])
#@login_required
#def movie():
#    if request.method == "GET":
        #ログインユーザーに紐づく全ての映画を取得
#        movie = Movie.query.where(Movie.user_id == current_user.id).all()
#        return render_template("record/record.html", movie=movie)

@movie_bp.route("/movie/<int:id>", methods=["GET", "POST"])
@login_required
def movie_works(id):
    form = MovieForm(request.form)
    if request.method == "GET":
        #TMDbAPIで映画詳細情報取得
        movie = api3.movies_get_details(movie_id=id, language="ja-JP")
        #映画個別詳細画面
        return render_template("movie/movie_works.html", movie=movie, form=form)
    
    if request.method == "POST" and form.validate_on_submit():

        #値を変数に割り当て(title=映画タイトル, overview=あらすじ, comment=映画に対するコメント, date=見た日付, poster_path=ポスター画像, api独自の映画ナンバー)
        title = form.title.data
        overview = form.overview.data
        comment = form.comment.data
        date = form.date.data
        poster_path = form.poster_path.data
        movie_number = id

        #Movieテーブルにレコード挿入
        Movie.add_movie(title, overview, comment, date, movie_number, poster_path, current_user.id)
        
        return redirect(url_for("record.record"))

app/src/templates/movie/movie.html
{% from 'bootstrap5/form.html' import render_form %}
{% from 'bootstrap5/utils.html' import render_messages %}
{% from 'bootstrap4/utils.html' import render_icon %}
{% extends "base.html" %}

{% block title %}
Movie-Record-App_movie
{% endblock %}

{% block content %}
    <div class="container text-center">
        {% if movies %}
            <p class="m-4 fs-2 fw-bold">検索結果</p>
        {% else %}
            <p class="fs-1">{{ render_icon('emoji-dizzy') }}</p>
            <p class="m-4 fs-2 fw-bold">検索結果はありません</p>
        {% endif %}

        <div class="row justify-content-md-center gap-4">
            {% if movies %}
                {% for movie in movies %}
                    <div class="card col-md-auto" style="width: 18rem;">
                        <a href="{{url_for('movie.movie_works', id=movie['id'])}}">
                            <img src="https://image.tmdb.org/t/p/w300{{movie['poster_path']}}" class="card-img-top ounded img-thumbnail  mx-auto d-block">
                            <div class="card-body">
                                <h5 class="card-title">{{ movie["title"] }}</h5>
                                <p class="card-text txt-limit"><p class="fw-bold">作品情報</p>{{ movie["overview"] }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}

app/src/templates/movie/movie_works.html
{% from 'bootstrap5/form.html' import render_form %}
{% from 'bootstrap5/utils.html' import render_messages %}
{% extends "base.html" %}

{% block title %}
Movie-Record-App_movie-works
{% endblock %}

{% block content %}
    <div class="container">
        {% if movie %}
        
            {% if movie['poster_path'] %}
            <div class="m-4">
                <img src="https://image.tmdb.org/t/p/w300{{movie['poster_path']}}" class="rounded img-thumbnail  mx-auto d-block">
            </div>
            {% endif %}
        
        
            <form method="POST">
                {{ form.csrf_token }}
                <div class="text-center pb-4">
                    <p class="fs-4 fw-bold">タイトル</p>
                    {{ movie['title'] }}
                </div>

                {#form.titleはhiddenタグ #}
                {{ form.title(value=movie['title']) }}

                <div  class="text-center pb-4">
                        <p class="fs-4 fw-bold">作品情報</p>
                        {{ movie['overview'] }}
                </div>

                {#form.overviewはhiddenタグ #}
                {{ form.overview(value=movie['overview']) }}

                {#form.poster_pathはhiddenタグ #}
                {{ form.poster_path(value=movie['poster_path']) }}

                <div  class="text-center pb-4">
                    <p class="fs-4 fw-bold">コメント</p>
                    {{ form.comment }}
                </div>
                <div  class="text-center pb-4">
                    <p class="fs-4 fw-bold">鑑賞日付</p>
                    {{ form.date }}
                </div>
                <div class="d-grid gap-2 col-6 mx-auto">
                    <input type="submit" class="btn btn-outline-primary" value="登録">
                </div>
            </form>
        {% endif %}
    </div>
{% endblock %}